[workspace]
resolver = "2"
members = [
    "crates/sentinel-core",
    "crates/sentinel-realtime",
    "crates/sentinel-quarantine",
    "crates/sentinel-updater",
    "crates/sentinel-yara",
    "crates/sentinel-pe",
    "crates/sentinel-definitions",
    "crates/sentinel-cli",
    "crates/sentinel-gui",
    "crates/sentinel-service",
    "crates/sentinel-telemetry",
    "crates/sentinel-behavior",
    "crates/sentinel-amsi",
    "crates/sentinel-memory",
    "crates/sentinel-minifilter-client",
    "crates/sentinel-etw",
    "crates/sentinel-reputation",
    "crates/sentinel-ransomware",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["BDFR"]

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "fs", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sha2 = "0.10"
md-5 = "0.10"
uuid = { version = "1", features = ["v4", "serde"] }
semver = { version = "1", features = ["serde"] }
notify = "8.2.0"
ed25519-dalek = "2.1"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
eframe = "0.31"
rfd = "0.15"
sysinfo = "0.37"
windows-service = "0.8"
yara-x = "1.20"
libloading = "0.8"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Registry", "Win32_System_Threading"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
